version: "3.9"

services:


  minio:
    restart: always
    user: "1001:1001"
    image: minio/minio
    container_name: mlflow_minio
    volumes:
      - ./minio_data:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    networks:
      - frontend
      - backend
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ADDRESS=${MINIO_ADDRESS}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_STORAGE_USE_HTTPS=${MINIO_STORAGE_USE_HTTPS}
      - MINIO_CONSOLE_ADDRESS=${MINIO_CONSOLE_ADDRESS}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-client:
    image: minio/mc
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ADDRESS=${MINIO_ADDRESS}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_STORAGE_USE_HTTPS=${MINIO_STORAGE_USE_HTTPS}
      - MINIO_CONSOLE_ADDRESS=${MINIO_CONSOLE_ADDRESS}
    networks:
      - backend


  init-minio:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        echo 'Waiting for MinIO...';
        sleep 5;
        mc alias set localminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        mc mb --ignore-existing localminio/${MINIO_BUCKET_NAME};
        echo 'Buckets on localminio:';
        mc ls localminio;
      "
    networks:
      - backend
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}

  mlflow_server:
    restart: always
    build: ./mlflow
    image: mlflow_server_with_boto3
    container_name: mlflow_server
    ports:
      - "${MLFLOW_PORT}:5000"
    networks:
      - frontend
      - backend
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:${MINIO_PORT}
      - MLFLOW_S3_IGNORE_TLS=true
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_S3_SIGNATURE_VERSION=s3v4
      - AWS_S3_ADDRESSING_STYLE=path
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow_data/mlflow.db
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination s3://${MINIO_BUCKET_NAME}
    volumes:
      - ./mlflow_data:/mlflow_data
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MLFLOW_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3


  nginx:
    image: nginx:stable-alpine
    container_name: mlflow_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./certbot_data:/etc/letsencrypt  # shared with Certbot
    depends_on:
      - mlflow_server
    networks:
      - backend

  certbot:
    build: ./certbot
    container_name: certbot
    environment:
      - PORKBUN_API_KEY=${PORKBUN_API_KEY}
      - PORKBUN_SECRET_API_KEY=${PORKBUN_API_SECRET}
    volumes:
      - ./certbot_data:/etc/letsencrypt  # shared with nginx
    command: >
      certonly
             --non-interactive
             --agree-tos
             --email topiko1987@gmail.com
             --dns-porkbun-credentials /etc/letsencrypt/creds.ini
             --preferred-challenges dns
             --authenticator dns-porkbun
             --dns-porkbun-propagation-seconds 60
             -d ml.twohands.dev

volumes:
  db_data:
  minio_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
